[package]
name = "sabiwm"
version = "0.0.1"
authors = ["Simon Wollwage <mail.wollwage@gmail.com>"]

[dependencies]
error-chain ="0.7"
slog = "1.3"
slog-json = "1.2"
slog-scope = "0.2"
slog-stream = "1.2"
xcb = "0.7"
xdg = "2.0.0"
